from ..strategies.spu_strategy import spu_strategy
from ..strategies.nwr_strategy import nwr_strategy
from ..strategies.spt_strategy import spt_strategy
from ..strategies.opt_strategy import opt_strategy
from ..strategies.opu_strategy import opu_strategy
from ..strategies.swr_strategy import swr_strategy
from ..strategies.swt_strategy import swt_strategy
from ..strategies.owt_strategy import owt_strategy
from ..strategies.pwr_strategy import pwr_strategy
from ..strategies.owr_strategy import owr_strategy
from ..strategies.per_strategy import per_strategy
from ..strategies.rec_strategy import rec_strategy
from ..strategies.alt_strategy import alt_strategy
from ..strategies.orn_strategy import orn_strategy
from ..strategies.rev_strategy import rev_strategy
from ..strategies.com_parser import com_parser
from ..strategies.ver_parser import ver_parser
from ..strategies.xrf_parser import xrf_parser
